  -- ######################################################
  -- ##### Criação tabelas para Challenge Engineer -- #####
  -- ##### Autor: Plínio Nunes Torres Junior       -- #####
  -- ##### Data Criação: 14/07/2024                -- #####
  -- ##### Data Ültima Alteração: 14/07/2024       -- #####
  -- ##### IDe Utilziada: Big Query                -- #####
  -- ######################################################
  
CREATE OR REPLACE TABLE
  CATEGORIA_TABLE (ID_SITE STRING(10),
    CODIGO_CATEGORIA_L1 INTEGER NOT NULL,
    NOME_CATEGORIA_L1 STRING(100) NOT NULL,
    CODIGO_CATEGORIA_L2 INTEGER NOT NULL,
    NOME_CATEGORIA_L2 STRING(100) NOT NULL,
    CODIGO_CATEGORIA_L3 INTEGER NOT NULL,
    -- Primary Key Table
    NOME_CATEGORIA_L3 STRING(100) NOT NULL);
CREATE OR REPLACE TABLE
  ORDERS_TABLE (
    -- Primary Key Table
    ID_ORDER INTEGER NOT NULL,
    -- Foreign Key Table: Customer
    ID_SITE_SEL STRING (10) NOT NULL,
    -- Foreign Key Table: Customer
    ID_CUSTOMER_SEL INTEGER NOT NULL,
    -- Foreign Key Table: Customer
    ID_SITE_BUY STRING(10) NOT NULL,
    -- Foreign Key Table: Customer
    ID_CUSTOMER_BUY INTEGER NOT NULL,
    -- Foreign Key Table: Item
    ID_ITEM INTEGER NOT NULL,
    -- Foreign Key Table: Item
    ID_VARIACAO INTEGER NOT NULL,
    -- Foreign Key Table: Categoria
    CODIGO_CATEGORIA_L3 INTEGER NOT NULL,
    -- Foreign Key Table: Item
    VALOR_ITEM FLOAT64 NOT NULL,
    VALOR_DESCONTO FLOAT64,
    VALOR_FRETE FLOAT64,
    VALOR_TOTAL FLOAT64,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_PAGAMENTO DATETIME,
    DATA_CANCELAMENTO DATETIME,
    -- Foreign Key Table: Meio_Pagamento
    ID_PAGAMENTO STRING (100),
    VALOR_PAGAMENTO FLOAT64,
    STATUS_ORDER STRING(100));

CREATE OR REPLACE TABLE
  CUSTOMER_TABLE ( ID_CUSTOMER INTEGER NOT NULL,
    ID_SITE STRING(10) NOT NULL,
    USER_NAME STRING (100) NOT NULL,
    NOME STRING(100) NOT NULL,
    SOBRENOME STRING(500) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TIPO_USUARIO STRING (150) NOT NULL,
    NUMERO_DOCUMENTO INTEGER NOT NULL,
    LOGRADOURO STRING (1000) NOT NULL,
    BAIRRO STRING (150) NOT NULL,
    CIDADE STRING (150) NOT NULL,
    CEP INTEGER NOT NULL,
    COD_AREA_TELEFONE INTEGER NOT NULL,
    TELEFONE INTEGER NOT NULL,
    DATA_CRICAO_CONTA DATETIME NOT NULL,
    DATA_DESATIVACAO_CONTA DATETIME );

CREATE OR REPLACE TABLE
  ITEM_TABLE ( ID_ITEM INTEGER NOT NULL,
    ID_SITE STRING(10) NOT NULL,
    ID_VARIACAO INTEGER,
    NOME_ITEM STRING(1000) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_DESATIVACAO DATETIME,
    DATA_AUTALIZACAO DATE,
    STATUS_ITEM STRING(100),
    -- Foreign Key Table: Categoria
    CODIGO_CATEGORIA_L3 INTEGER NOT NULL,
    VALOR_ITEM FLOAT64 NOT NULL,
    CONDICAO_ITEM STRING (10) NOT NULL,
    MARCA STRING (10) NOT NULL,
    MODELO STRING(10) NOT NULL,
    PESO FLOAT64 NOT NULL);

CREATE OR REPLACE TABLE
  ITEM_PH_TABLE ( PHOTO_DATE DATE NOT NULL,
    ID_ITEM INTEGER NOT NULL,
    ID_SITE STRING(10) NOT NULL,
    ID_VARIACAO INTEGER,
    NOME_ITEM STRING(1000) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_DESATIVACAO DATETIME,
    DATA_ATUALIZACAO DATE,
    STATUS_ITEM STRING(100),
    -- Foreign Key Table: Categoria
    CODIGO_CATEGORIA_L3 INTEGER NOT NULL,
    VALOR_ITEM FLOAT64 NOT NULL,
    CONDICAO_ITEM STRING (10) NOT NULL,
    MARCA STRING (10) NOT NULL,
    MODELO STRING(10) NOT NULL,
    PESO FLOAT64 NOT NULL);
    
CREATE OR REPLACE TABLE
  MEIO_PAGAMENTO_TABLE ( ID_PAGAMENTO INTEGER NOT NULL,
    ID_SITE STRING(10) NOT NULL,
    NOME_TIPO_PAGAMENTO STRING(1000) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_DESATIVACAO DATETIME);
